packages:
  - software
  - workflow
  - model
  - ui
  - test
  - block

catalog:
  "@platforma-sdk/model": ^1.23.0
  "@platforma-sdk/ui-vue": ^1.23.0
  "@platforma-sdk/workflow-tengo": ^2.16.0
  "@platforma-sdk/block-tools": ^2.5.21
  "@platforma-sdk/test": ^1.23.0
  "@platforma-sdk/tengo-builder": ^1.19.2
  "@platforma-sdk/package-builder": ^2.15.4
  "@milaboratories/graph-maker": ^1.1.57
  '@platforma-sdk/eslint-config': ^1.0.1

  '@milaboratories/software-pframes-conv': ^2.1.18
  '@platforma-open/milaboratories.software-small-binaries': ^1.15.19
  "@platforma-open/milaboratories.runenv-python-3": ^1.1.7
  
  "vue": ^3.5.13
  "vue-tsc": ^2.2.0
  
  "typescript": ~5.5.4
  "tsup": ~8.3.5
  "turbo": ^2.4.4

  "vite": ^6.1.0
  "vitest": ^3.0.5
  "@vitejs/plugin-vue": ^5.2.1

  "@changesets/cli": ^2.28.1
